### ISSUE TITLE
Error when trying to remove/rename elements in section restricted with cohort access

### ISSUE THREAD

**Issue by peterhuppertz** [moodle-an-hochschulen/moodle-availability_cohort#4] opened 2021-01-25 09:11 UTC
I have a section of a course restricted to a cohort. If a person with manager role tries to add content it's all fine, however, when he tries to rename/delete content he receives the following error:
```
Error code: codingerror
* line 498 of /lib/pagelib.php: coding_exception thrown
* line 830 of /lib/pagelib.php: call to moodle_page->magic_get_context()
* line 1456 of /lib/weblib.php: call to moodle_page->__get()
* line 169 of /availability/condition/cohort/classes/condition.php: call to format_string()
* line 159 of /availability/classes/condition.php: call to availability_cohort\condition->get_description()
* line 526 of /availability/classes/tree.php: call to core_availability\condition->get_standalone_description()
* line 476 of /availability/classes/tree.php: call to core_availability\tree->get_full_information_recursive()
* line 216 of /availability/classes/info.php: call to core_availability\tree->get_result_information()
* line 2774 of /lib/modinfolib.php: call to core_availability\info->is_available()
* line 2737 of /lib/modinfolib.php: call to section_info->get_available()
* line 1900 of /lib/modinfolib.php: call to section_info->__get()
* line 1921 of /lib/modinfolib.php: call to cm_info->obtain_dynamic_data()
* line 1234 of /lib/modinfolib.php: call to cm_info->get_user_visible()
* line 3030 of /lib/moodlelib.php: call to cm_info->__get()
* line 515 of /lib/externallib.php: call to require_login()
* line 91 of /course/classes/output/course_module_name.php: call to external_api::validate_context()
* line 3776 of /course/lib.php: call to core_course\output\course_module_name::update()
* line 8059 of /lib/moodlelib.php: call to core_course_inplace_editable()
* line 478 of /lib/external/externallib.php: call to component_callback()
* line 261 of /lib/externallib.php: call to core_external::update_inplace_editable()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```

He has all the rights for cohort:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/5812004/105684718-9d0ff800-5ef5-11eb-8509-4ea91ad577ca.png">

What could be the problem?

As admin I can rename/remove content without problems. Once the restriction is removed also managers can rename/remove content.

**Comment by abias** [comment] 2022-07-22 19:31
Hi @peterhuppertz ,

I am sorry that this issue remained unhandled up to now. I tried to reproduce your issue, but the reproduction steps were not fully clear and I was not able to reproduce it.

May I ask you to test this issue again in a fresh Moodle installation (so that the manager role is unchanged) with the latet version of this plugin? If you can still reproduce this issue, please provide detailed steps to reproduce.

Thanks,
Alex

**Comment by abias** [comment] 2023-03-19 10:11
I close this issue as there wasn't any feedback anymore.

**Closed as completed by abias** 2023-03-19 10:11 UTC
